// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwuenhictjprfbktfzjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3dWVuaGljdGpwcmZia3Rmemp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzgzODgsImV4cCI6MjA2NTU1NDM4OH0.lC3XNxmRLE26YPISup_jSntqhY-D5MPh0EJzoWbjHA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);